version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev # 启动命令待后端项目初始化后确定

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite 默认端口
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    command: npm run dev # 直接使用npm run dev命令启动开发服务器

networks:
  default:
    driver: bridge